server:
    port: 10003
spring:
    application:
        name: gateway-server
    boot:
        admin:
            client:
                url: http://localhost:10002
    cloud:
        gateway:
          routes:
          - id: rewritepath_route
            uri: http://localhost:10000
            predicates:
            - Path=/eureka/**
            filters:
            - RewritePath=/eureka/(?<segment>.*), /$\{segment}
eureka:
    instance:
        appname: gateway-server
    client:
        serviceUrl:
            defaultZone: http://localhost:10000/eureka/
    server:
        eviction-interval-timer-in-ms: 5000
management:
    endpoints:
        web:
            exposure:
                include: '*'
        health:
            show-details: ALWAYS
